### ISSUE TITLE
Profile card #1

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#1]
## Value statement
As a **new bootcamp member** and/or as an **alumni**
I need to see  the **profile cards** of neuefische members 
so that I can **view their profiles, projects and get in touch with them** 

## Description (Text, Scribble, Wireframe, Design)
- A profile card contains a profile picture and several information such as:
   - new fish vs. alumni fish, workplace, contact, capstone project, personal website, project-links and skill tags

![IMG_20200229_140347](https://user-images.githubusercontent.com/59569402/75624905-32f1b480-5bb9-11ea-8317-1970dcdfb4bf.jpg)

## Acceptance criteria
- [x] Profile card text is in a good readable size
- [x] Profile picture and sub-information are visible
- [x]  Profile cards are scrolled vertically
- [x] Profile cards have to be visually separated

## Tasks

- [x]  Create json file with necessary data of min. 2 alumnis and 2 new fishes
- [x]  Create profile card
- [x]  Create cards of several members
- [x]  Create necessary components
- [x]  Styling
- [x]  Test in mobile and desktop view

## Size
large
