### ISSUE TITLE
Firebase hosting

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#12]
## Value statement
As a **user**
I need to have access to the website via url
so that I can view the page in every browser

## Acceptance criteria
- [x] website should be hosted on firebase
- [x] security measures should taken care of

## Tasks

- [x] hoste website on firebase
- [x]  generate key
- [x]  generate env file for security measure
- [x] put firebase files into gitignore

## Size
medium
