### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#13]
## Value statement
As a **user**
I need to see and add my newly created profile card in the profile card pool

## Acceptance criteria
- [x] newly created cards should be visible after refreshing the browser

## Tasks

- [x] save card to local storage
- [x] load card from local storage

## Size
small
