### ISSUE TITLE
Style radio & checkbox buttons

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#14]
## Value statement
As a **user**
I need big enough buttons to choose easily btw. options

## Description (Text, Scribble, Wireframe, Design)
![IMG_20200315_152728](https://user-images.githubusercontent.com/59569402/76703417-e1c1e480-66d1-11ea-9520-939661a7bc91.jpg)

## Acceptance criteria
- [x] The button which is clicked should signalize by its color that it's chosen
- [x] Only one radio box can be active/chosen at a time
- [x] Several checkboxes can be chosen at once

## Tasks

- [x] style radio buttons that only one box can be chosen at a time
- [x] style checkbox buttons that several boxes can be chosen
- [x] add button component to storybook
- [x] test that checked boxes are rendered correctly 

## Size
medium
