### ISSUE TITLE
Delete Card

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#15]
## Value statement
As a **user**
I need to be able to delete my profile card  

## Description (Text, Scribble, Wireframe, Design)
![IMG_20200315_171408](https://user-images.githubusercontent.com/59569402/76705466-81866f00-66e0-11ea-83c2-6eb7094b8f20.jpg)

## Acceptance criteria
- [x] The selected card x will be deleted

## Tasks

- [x] create a delete button
- [x] add logic to delete the selected card

## Size
small
