### ISSUE TITLE
Select favorites

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#16]
## Value statement
As a **user**
I need to be able to select my favorite profiles to have faster access to

## Description (Text, Scribble, Wireframe, Design)
![IMG_20200315_184444](https://user-images.githubusercontent.com/59569402/76707137-1d1ddc80-66ed-11ea-9ac6-ecc7bafd75b2.jpg)

## Acceptance criteria
- [x] The tag which is clicked will appear on the page "/favorites"
- [x] On "/favorites" if you untoggle the tag the selected profile disappears

## Tasks

- [x] create a marking symbol
- [x] create a  new page "/favorites"
- [x] add toggle logic

## Size
medium
