### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#25]
## Value statement
As a **user**
I need to be able to search for a specific user

## Acceptance criteria
- [ ] when you type a keyword into the search bar all matching results/ cards will be shown
- [ ] keywords will be highlighted

## Tasks

- [ ] create an input field
- [ ] create a search button with a search icon
- [ ] create a delete button to empty the search
- [ ] add search logic

## Size
medium
