### ISSUE TITLE
Edit function

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#27]
## Value statement
As a **user**
I need to be able to edit my profile card
so that I can update information

## Acceptance criteria
- [x] when edit button is clicked the user will be redirected to "/edit-page" 
- [x] the form is filled with the data from that profile card
- [x] on click on the Safe Changes button the profile card will be updated and the user will be redirected to "/pool-page"

## Tasks

- [x] create an edit button
- [x] on click on the edit button the user will be redirected to "/edit-profile"
- [x] add logic that form is filled with information of that card
- [x] create a Save Changes button

## Size
medium
