### ISSUE TITLE
Create list of cards

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#3]
## Value statement
As a **new bootcamp member** and/or as an **alumni**
I need to see  the **profile cards** of neuefische members 
so that I can **view their profiles, projects and get in touch with them** 

## Description (Text, Scribble, Wireframe, Design)
- Each profile card contains a profile picture and several information such as:
   - new fish vs. alumni fish, workplace, contact, capstone project, personal website, project-links and skill tags

## Acceptance criteria
- [ ] Profile cards have to be visually separated
- [ ] Profile card text is in a good readable size
- [ ] Profile picture and sub-information are visible
- [ ]  Profile card are scrolled vertically

## Tasks
 Create json file with necessary data of min. 2 alumnis and 2 new fishes
 Create cards of several members
Test in mobile and desktop view

## Size
small
