### ISSUE TITLE
Toggle profile card

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#4]
## Value statement 
As a **user**
I do **not need to see detailed information** straight ahead 
so that I **don't have to scroll long to see the next profile**

## Description (Text, Scribble, Wireframe, Design)
There will be a button [View profile] resp. [Hide profile]
## Acceptance criteria

- [ ]  Profile details are hidden by default
- [ ]  Button text changes on tap
- [ ]  Each card expands in place

## Tasks

- [ ]  Create button component
- [ ]  Add toggle logic
- [ ]  Finish styling
- [ ]  Test with a few cards on mobile and desktop

## Size
medium
