### ISSUE TITLE
Profile picture, link functionality #2

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#5]
## Value statement
As a **user**
I need to see a personal profile picture and follow the links displayed on the card
so that I can **view projects and contact members via email** 

## Description (Text, Scribble, Wireframe, Design)
- Each profile card contains several links and several icons, individual picture
![IMG_20200229_140347](https://user-images.githubusercontent.com/59569402/75624905-32f1b480-5bb9-11ea-8317-1970dcdfb4bf.jpg)

## Acceptance criteria
- [x] Links should be clickable - whereas some links are optional regarding user
- [x] Icons should be in a good size and should only be visible when user provided this information
- [x] Each card should have an individual picture

## Tasks

- [x] Render hrefs, that links are clickable
- [x]  external urls can be followed
- [x]  an email can be sent
- [x] Create and insert icons
- [x] Add individual profile picture
- [x] Add Styling where needed

## Size
medium
