### ISSUE TITLE
Toggle profile details #3

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#6]
## Value statement 
As a **user**
I do **not need to see detailed information** straight ahead 
so that I **don't have to scroll long to see the next profile**

## Description (Text, Scribble, Wireframe, Design)
There will be a button [View profile] resp. [Hide profile]
![IMG_20200301_132956](https://user-images.githubusercontent.com/59569402/75625709-02ae1400-5bc1-11ea-83f5-6be79976d74a.jpg)

## Acceptance criteria

- [x]  Profile details are hidden by default
- [x]  Each card expands in place

## Tasks

- [x]  Create button component
- [x]  Add toggle logic
- [x]  Finish styling
- [x]  Test with a few cards on mobile and desktop

## Size
medium
