### ISSUE TITLE
Create profile card #4

### ISSUE THREAD

**Issue by evabrinkmann** [evabrinkmann/capstone-project#7]
## Value statement
As a **user**
I need to be able to **create my own profile card*
so that I can **share my contact, project and work details**

## Description (Text, Scribble, Wireframe, Design)
A form to fill in my personal details
Checkboxes to check
Picture upload/take picture
A button to submit [Create profile]
![IMG_20200301_144017](https://user-images.githubusercontent.com/59569402/75627885-63931780-5bd4-11ea-9629-657a009ad3d7.jpg)

## Acceptance criteria

- [x]  The form is found at the path "/create-profile"
- [x]  The form is only submitted when all requested fields are filled
- [x]  The form reacts on submit (Enter key or button press)
- [x]  The first input has focus at start and after submit
- [x]  The form is cleared after submit
- [x]  The new card is added at the beginning

## Tasks
 Add routing/navigation
 Create form component
 Add styling
 Test on mobile and desktop
## Size
large
